{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Values.ingress.name }}"
  # annotations are part of the metadata object
  # usually annotations are used to sent information to a controller
  # here we instruct the ingress-controller to set the connect-timeout to 60s and rewrite the target to '/' for this specific host/URL
  annotations:
    nginx.ingress.kubernetes.io/proxy-connect-timeout: 60s
    nginx.ingress.kubernetes.io/rewrite-target: /
# define the routing rules for the ingress in its 'spec'
spec:
  rules:
    # an ingress can have one to many hosts. A host is fully quallified URL
    # TODO: replace in ingress host URL the <participantId>, <cluster-name> and <project-name> parameters of the training cluster 
    # e.g. '0007-simple-nginx.ingress.wdfcw48.k8s-train.shoot.canary.k8s-hana.ondemand.com'
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      # the ingress controller routes traffic to a service backend based on a <host>/<path> combination
      # in this case traffic coming in to <host>/my-app will be routed to the service 'simple-nginx-service'
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sample-service
            port:
              number: {{ .Values.ingress.port }}
{{- end }}