{{- with .Values.imagePullSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson:  {{ template "imagePullSecrets" . }}
{{- end }}
# kubectl create secret docker-registry NAME --docker-username=user --docker-password=password --docker-email=email [--docker-server=string] [--from-literal=key1=value1] [--dry-run] 
#   tls.crt: {{ werf_secret_file "backend-saml/stage/tls.crt" | b64enc }}
#   tls.key: {{ werf_secret_file "backend-saml/stage/tls.key" | b64enc }}